### ISSUE TITLE
Are you the iHex on MacAppStore?

### ISSUE THREAD

**Issue by Oyangiz** [ridiculousfish/HexFiend#76] opened 2017-03-04 07:02 UTC
Are you the iHex on MacAppStore?
I found it and it looks like HexFiend, but I can not found the license and this project name.
Is it a copier？
<img width="396" alt="jietu20170304-145708" src="https://cloud.githubusercontent.com/assets/11882176/23576873/a0a5af80-00eb-11e7-8d90-95aea2047e92.png">

**Comment by nlsn** [comment] 2017-03-13 14:04
I'm also curious if iHex is copied from Hex Fiend. They appear to be the same.

**Comment by ridiculousfish** [comment] 2017-03-14 07:32
Yeah, there's at least one repackaged Hex Fiend :(

**Comment by nlsn** [comment] 2017-03-14 12:11
Makes me wonder what nefarious crap may have been added in the repackaging process.

**Comment by tholu** [comment] 2017-03-15 09:29
Duplicate of https://github.com/ridiculousfish/HexFiend/issues/59.

**Closed** 2017-03-15 16:24 UTC
