### ISSUE TITLE
What happened to the ARC branch?

### ISSUE THREAD

**Issue by JanX2** [ridiculousfish/HexFiend#33] opened 2014-07-04 08:33 UTC

**Comment by kainjow** [comment] 2016-11-15 18:01
Closing this. ARC changes will continue to occur (slowly though), and pull requests are always welcomed. The problem is making mass changes to the code will most likely result in bugs, so they need to be done carefully and in small chunks at a time.

**Closed by kainjow** 2016-11-15 18:01 UTC

**Comment by kainjow** [comment] 2017-04-03 00:22
HF is now 95% ARC. There are only 4 remaining files to convert in the framework, but these are the most difficult due to mixing Objective-C objects with C data structures, or with CoreFoundation collections. I'll get to them eventually.

I nearly completed converting HFByteArray_FileWriting.m but came across an issue where `createAcyclicGraphFromStronglyConnectedComponents()` creates `dependencies` and `dependencyObjects` variables, then iterates over them, but never references them. There have been no reports on file writing not working, so I'm not sure what's going on with this code.

**Comment by kainjow** [comment] 2018-01-06 20:21
HF is now 100% ARC 🎉
