### ISSUE TITLE
[FEAT.REQ.] Custom data structs?

### ISSUE THREAD

**Issue by apollolux** [ridiculousfish/HexFiend#89] opened 2017-05-24 04:53 UTC
Hello! So far Hex Fiend does what I ask it to regarding hex editing. I used to use 010 Editor on one of my old comps because it had/still has the ability to read data into custom views, currently implemented as "binary templates," text files with C-like structs. Some of the files I view often have, for example, { length, data[ length ] } byte arrays as "strings" for reasons, and making custom views of these would allow me to use Hex Fiend to read them instead of hacking my own one-off byte readers.

Thanks in advance for considering my request! Please keep up the good work, y'all!

**Comment by kainjow** [comment] 2017-06-14 15:26
I've worked on a similar feature before for a proprietary product, and Lua was used for the templating language. Too bad Javascript doesn't support 64-bit numbers, otherwise JavaScriptCore could be used as the template language.

It's a big feature. However, starting with a read-only implementation would be simpler than full on read-write.

**Comment by kainjow** [comment] 2017-06-14 16:18
[ChaiScript](http://chaiscript.com) would be a neat language to use. Just needs a Objective-C wrapper.

**Comment by gingerbeardman** [comment] 2017-07-10 14:10
Would appreciate this also.

I hack a lot of classic videogame saves, and it would be great to be able to present them with custom views.

**Comment by kainjow** [comment] 2017-07-10 23:04
I started working on this the other day. Will keep posted on updates.

**Comment by gingerbeardman** [comment] 2017-07-11 14:34
I don't mind hacking the grammer manually at first.

Are you planning on it being some widgets in an area like the Data Inspector?

**Comment by kainjow** [comment] 2017-07-11 20:51
Haven't thought about UI too much yet. What I started on was a parser for the template format [WinHex](https://www.x-ways.net/winhex/templates/)  uses (my code can tokenize three example files I found). I decided against using a third-party programming language to keep the code simpler and reduce dependencies. I may contact WinHex to see what they think about creating a shared repository of templates that could be used with WinHex or Hex Fiend. I figure why reinvent the wheel here. Ideally the language used would be independent from the implementation, so if another format wanted to be added it could (for example 010 Editor).

**Comment by gingerbeardman** [comment] 2017-07-12 10:19
We're in safe hands!

**Comment by gingerbeardman** [comment] 2017-08-30 10:28
Back in Synalyze today to do more of this and it's a real pain! patiently waiting for an alterantive.

**Comment by follower** [comment] 2018-01-01 11:43
Would be cool to support http://kaitai.io/ as it's an attempt to create a cross-application/cross-language way to specify a file format and then generate parsers in multiple languages.

Supporting it would provide access to the existing library of formats.

**Comment by kainjow** [comment] 2018-01-02 03:48
@follower based on my understanding Kaitai seems to not really work in the way Hex Fiend would need. It looks to require compiling (via Java...) the language files into a programming language, instead of interpreting the language file at runtime, which is how almost all other binary template languages work that I've seen.

**Comment by kainjow** [comment] 2018-01-07 08:55
I scrapped my original idea of implementing a new language from scratch, and am experimenting with using [Tcl](https://www.tcl.tk) because it's built-in to the Mac so it's easy to use without having to compile another library into HF and add bloat/complexity. My work is in the binary-templates branch if you want to take a look.

Here's a screenshot of the very basic UI I've got so far (currently just loads a hard coded path):

![templatepreview](https://user-images.githubusercontent.com/271035/34647925-bab04bf0-f344-11e7-8137-f4e0eea72d65.png)

Using this Tcl script:

```tcl
uint64 "Magic"
uint32 "Chunk Length"
uint32 "Chunk Type"
```

I have all the int sizes implemented, and will add more types. Also will add groups.

Tcl is actually quite nice and simple, and it has the benefit of supporting all ints of any size. Plus almost any text editor supports syntax highlighting.

**Comment by kainjow** [comment] 2018-01-08 02:17
More flushed out example of a basic PNG parser:

```tcl
big_endian
requires 0 "89 50 4E 47 0D 0A 1A 0A"
hex 8 "Signature"
while {![end]} {
    set chunk_len [uint32 "Chunk Length"]
    set chunk_type [ascii 4 "Chunk Type"]
    if {$chunk_type == "IHDR"} {
        uint32 "Width"
        uint32 "Height"
        uint8 "Bit Depth"
        uint8 "Color Type"
        uint8 "Compression Method"
        uint8 "Filter Method"
        uint8 "Interlace Method"
    } else {
        move $chunk_len
    }
    hex 4 "CRC"
}
```

**Comment by kainjow** [comment] 2018-01-14 21:28
Just posted the first beta here: https://github.com/ridiculousfish/HexFiend/releases/tag/v2.9.0b1

**Comment by gingerbeardman** [comment] 2018-01-17 22:51
I've just been trying it out. This is really promising! Nice work.

It's a bit odd that the contents of the template panel depends on the position of the cursor - there's nothing to tell you that. For example I have to position the cursor at the start of the file for the PNG template to show anything useful.

It would be good to be able to select ranges of data and then, somehow, add that to the template. So you create the tcl/template interactively.

The way I am imagining you could create the PNG template using the mouse:

* open PNG
* select the first 0x8 bytes
* a new entry appears in the template panel
  - ignore it and it will go away when your selection changes
  - interact with it and it becomes permanent (and editable after the fact, of course)
* rename the entry "Signature"
* choose a type for it

using the PNG template, this is what I would expect:

* panel shows template info at all times
* item in template that cursor is inside is highlighted 

so:

* position cursor at byte 0xB
* "Chunk Length" is highlighted in template panel
* I can choose a colour or presentation style for this entry

lots more thoughts on this, let me know if you want them!

**Comment by kainjow** [comment] 2018-01-20 23:55
I agree on the template moving based on cursor is a bit odd. I do want it to have the ability to render data based on a different position, but maybe by default it could be "anchored" to position 0, and offer a way to start at a different position, and/or provide a context menu to do this as well (e.g. "Anchor Template At Offset X").

I didn't have any plans for a UI to generate a template. I think if that was done, it'd come later, after the underlying code is more flushed out. Do other apps offer a UI to create a template? The problem is the format of the template. If Tcl is used, then now we need a Tcl parser, unless we just use another normal format, such as a plist. 

Maybe instead of a GUI HF could allow editing the template inside HF and offer a way to insert commands in a drop-down menu, provide syntax coloring, etc. A simple edit mode essentially. This would provide discoverability for commands and faster turnaround time to editing and previewing.

For auto-detecting a template, easiest would be for HF to match based on file extension. Each template could provide a list of file extensions, for example `extensions "jpg" "jpeg"`.

Regarding nesting, I think you can use the [source](https://www.tcl.tk/man/tcl8.4/TclCmd/source.htm) command, and put the templates into a custom [procedure](https://www.tcl.tk/man/tcl/TclCmd/proc.htm), and then call that procedure in the "main" code for each script. Would be interesting to see if it actually works based on relative paths.

> but can the template panel display everything we do in tcl?

I'm not sure what you mean. The template UI only shows results of commands that HF provides. All other commands currently do their default thing, for example if you used `puts` then it would go to standard output which you wouldn't see unless you ran HF's binary from the Terminal.

The resource fork example is very new, I still need to flush it out. Not much to see yet. Here's a screenshot though, using the new `section` command:

<img width="781" alt="resourcefork" src="https://user-images.githubusercontent.com/271035/35189193-67411f10-fdfa-11e7-9cff-6265141ce0b5.png">

**Comment by kainjow** [comment] 2018-01-21 06:42
Beta 2 posted: https://github.com/ridiculousfish/HexFiend/releases/tag/v2.9.0-beta-2

**Comment by gingerbeardman** [comment] 2018-01-21 10:29
Synalyze it! has a GUI to define a template (aka grammar)

https://www.synalysis.net/the-grammar-page.html

![GitHawk Upload by gingerbeardman](https://i.imgur.com/WjkfP9b.jpg)

**Comment by kainjow** [comment] 2018-04-09 01:15
Beta 3 posted: https://github.com/ridiculousfish/HexFiend/releases/tag/v2.9.0-beta-3

I'd like to make this an official release in the next few weeks.

**Comment by gingerbeardman** [comment] 2018-04-09 10:48
I'll take a look

**Comment by t089** [comment] 2018-04-16 12:35
Hey, I like the idea. I tested the beta3 but I only see a "Failed to read bytes while executing ..." error message.

<img width="827" alt="screenshot" src="https://user-images.githubusercontent.com/846537/38809261-45ba17da-4183-11e8-8056-503e1ad0bf3e.png">

`First.tcl` contains
```
uint32 "label"
```

macOS 10.13.4
Hex Fiend: Version 2.9 (180409)

**Comment by gingerbeardman** [comment] 2018-04-16 12:40
Something is wrong because the bundled PNG.tcl template no longer works, nor the Test.tcl to name but two.

![screen shot 2018-04-16 at 13 39 16](https://user-images.githubusercontent.com/49612/38809527-aec6ed14-417b-11e8-80b5-6c31a4dbbcdb.png)

**Comment by kainjow** [comment] 2018-04-23 00:54
Hmm I can reproduce with the release build, but not debug. Looking into it..

**Comment by shpeg** [comment] 2018-05-14 14:17
This feature is precisely what I need for reverse-engineering file-formats. Any progress on getting the release-build to work again?

**Comment by sandrewh** [comment] 2018-06-06 17:38
If you uncheck then recheck Views, Binary Templates (beta), the Template will work again.

![image](https://user-images.githubusercontent.com/575316/41055274-661bfa22-6986-11e8-962c-d1c2481b4c93.png)

**Comment by sandrewh** [comment] 2018-06-07 23:56
When the app is reopened after being closed with 'Binary Templates' open, the 'Binary Templates' is loaded before the normal hex data, and is stuck with an uninitialized byteArray.  If you hide and show 'Binary Templates', this forces them to pickup the correct hex data, because this is done well after app initialization.

**Comment by jcburns** [comment] 2018-06-11 18:38
The template system adds a whole new dimension and is encouraging me to dive into tcl...thanks! I have a semi-related question: how do you open the resource fork of a file in Hex Fiend? I tried the `/..namedfork/rsrc` stuff using the command line launcher, but got "LSOpenURLsWithRole() failed" (Error -54) Thanks again.

**Comment by kainjow** [comment] 2018-06-12 02:22
Ah, finally figured this release bug out. Debug builds have asserts that call extra code, so it was initializing the view early while release mode initializes after it's needed. Will fix shortly and post a new beta.

**Comment by kainjow** [comment] 2018-06-12 02:38
https://github.com/ridiculousfish/HexFiend/releases/tag/v2.9.0-beta-4 - please let me know if this works.

**Comment by gingerbeardman** [comment] 2018-06-18 14:16
Works for me. Nice to see 2.9 out

**Comment by bumblebritches57** [comment] 2018-06-24 18:30
@jcburns Resource Forks aren't POSIX, they're Classic Mac, POSIX tools for teh most part can't use them.

I remember reading up on this stuff and hearing there was some built in command to extract resource forks, but I've never needed it, so I don't remember what it was called, sorry dude.

Just poke around in that on the internet and you should find something.

**Comment by bumblebritches57** [comment] 2018-06-24 18:44
Can we get support for reading specific bits?

The formats I deal with are bit based, not byte based.

**Comment by bumblebritches57** [comment] 2018-06-24 18:46
@gingerbeardman Nahhhh Synalize it's gui is badly designed, but it exposes the right amount of info; file formats are complicated, a GUI that's too simple can't parse the majority of formats.

**Comment by kainjow** [comment] 2018-06-25 00:31
@bumblebritches57 can you give an example of what you're looking for, or how it'd be used?

**Comment by bumblebritches57** [comment] 2018-06-25 00:58
Basic bitwise operations.

For example:

Let's say I have a 4 byte file.

contained in that 4 bytes is 3 fields, the first field is 9 bits, the second is 1, and the third is 22 bits.

But honestly I'm already doing that with FoundationIO, so it's not a huge deal, I do know that Synalize It (I probably misspelled that...) does have this feature.

**Comment by kainjow** [comment] 2018-12-29 06:59
Closing, as binary templates have been added. Feel free to start new threads for new ideas/requests.

**Closed by kainjow** 2018-12-29 06:59 UTC
Labels: Feature
