### ISSUE TITLE
Selecting bytes with the keyboard can cause HexFiend to crash

### ISSUE THREAD

**Issue by floam** [ridiculousfish/HexFiend#62] opened 2016-03-16 12:22 UTC
I was using Hex Fiend to check up on  a bug I've experienced for years and found HF to be particularly  #affected.

This is an OS X bug that I've experienced on all my Macs since 10.5. Hex Fiend is somewhat useful to simply demo the bug, but does not respond well compared to other apps and and crashes quickly

Hit left shift + up arrow and than press backspace/delete (in the position above the enter key) while you are still pressing the first two keys/in Hex Fiend.

<img width="553" alt="screenshot 2016-03-16 at 4 50 06 am" src="https://cloud.githubusercontent.com/assets/291142/13811458/17035134-eb33-11e5-99ee-cb648862b577.png">

Something gets confused in the deletion behavior while the state is kind of unstable and it seems an control character gets left behind. You can see them in Hex Fiend. 7F7F7F. Focus the left panel and repeat to, clearing that text away and it then crashing.

This happens in lots of cocoa text input fields that are roughly supposed to be single-line vies of text a not multi-line ones. People who have a habit of using this key combo to clear buffers/fields have lots of strange unlucky things happen. For some reason I get 0x7F from Hex Fiend. I also got 0x7F in the earlier 10.5, 10.6 days of this bug.  But most apps today actually give me 0x08 chars, like the Safari Smart Search Field:  Trust me, they are right there, you just can't see them. 

<img width="164" alt="screenshot 2016-03-16 at 5 00 43 am" src="https://cloud.githubusercontent.com/assets/291142/13812099/3a2efb46-eb37-11e5-8254-676d44de90c6.png">

Easy to witness there with Google because Google receives the chracters as part of your query. It renders them a "?"s.  

Instead  command-A to select all. You can't see these, now, but it will oddly display this empty input area like the entire "nothing" is selected. Can copy and paste them anywhere.

<img width="566" alt="screenshot 2016-03-16 at 5 01 08 am" src="https://cloud.githubusercontent.com/assets/291142/13812147/a1ea8aca-eb37-11e5-9f91-f9732725a9fd.png">

Pasting these bytes from the Safari text field into HF can also cause an instant crash. 

<img width="1026" alt="screenshot 2016-03-16 at 5 05 34 am" src="https://cloud.githubusercontent.com/assets/291142/13811962/4dbcb028-eb36-11e5-804f-a3e840c56113.png">

[Hex Fiend_2016-03-16-034455_AaronBook.hang.zip](https://github.com/ridiculousfish/HexFiend/files/175929/Hex.Fiend_2016-03-16-034455_AaronBook.hang.zip)

Apple rdar://5288750 & rdar://21783531

**Comment by floam** [comment] 2016-03-16 12:42
Also can crash it in the Find window with a text search + that key combo.

**Comment by kainjow** [comment] 2016-03-16 16:59
What version of Hex Fiend are you using?

**Comment by floam** [comment] 2016-03-17 04:22
Built from HEAD.

**Comment by percontation** [comment] 2016-03-17 08:35
I couldn't reproduce this, probably because I'm doing it wrong.

**Comment by percontation** [comment] 2016-03-17 08:44
I'm having trouble reproducing this (probably due to an inability to following instructions).

![untitled](https://cloud.githubusercontent.com/assets/563506/13840745/a9f5f38a-ebe1-11e5-865b-aca85e09d93e.gif)

Anything obvious I'm doing wrong here? Maybe upload a similar video to help me out? :|

**Comment by floam** [comment] 2016-03-17 14:05
That looks right based on what I see flashing on the keyboard there. How are you getting it to flip to a full layout like that? I wonder if it has to do with the fact that on the Macbook Pro my "delete" key is the backspace key is the delete key. On the other layout what if you try the actual delete key? Is this on a MBP? Here's me doing it:

https://drive.google.com/open?id=0B9nS3wSv15QjZWdqUWRnVVoySVk

And here is what is recorded by the free "Key Codes" app on the Mac App Store if I press left shift, up key, delete. (then release delete, release shift, up, release shift).

```
Modifier Change
	Keys:		⇧
	Key Code:	65535 / 0xffff
	Modifiers:	196866 / 0x30102

Key Down
	Characters:	
	Unicode:		63232 / 0xf700
	Keys:		⇧↑
	Key Code:	126 / 0x7e
	Modifiers:	10682626 / 0xa30102

Key Down
	Characters:	
	Unicode:		127 / 0x7f
	Keys:		⇧⌫
	Key Code:	51 / 0x33
	Modifiers:	2294018 / 0x230102

Key Up
	Characters:	
	Unicode:		127 / 0x7f
	Keys:		⇧⌫
	Key Code:	51 / 0x33
	Modifiers:	2294018 / 0x230102

Key Up
	Characters:	
	Unicode:		63232 / 0xf700
	Keys:		⇧↑
	Key Code:	126 / 0x7e
	Modifiers:	10682626 / 0xa30102

Modifier Change
	Keys:		
	Key Code:	65535 / 0xffff
	Modifiers:	65792 / 0x10100
```

 I'll note that in the past I have found that installing [https://pqrs.org/osx/karabiner/](Karabiner) and having it active remapping anything makes the issue go away FWIW.

**Comment by percontation** [comment] 2016-03-17 23:16
You called it, I have Karabiner. I can get the 7Fs in HexFiend / 08s in Safari with it disabled. Seems kinda like the up+shift+backspace combo confuses Quartz into sending ASCII delete (or backspace?) as text.

I'm still not managing to cause a crash though :/

One difference I'm noticing: in your video, your shift+up selection is relocating the selected region without growing it (moving it back one line at a time), whereas when I try this my shift+up selection grows backwards one line at a time (eventually selecting the whole region). Maybe this is more related to the crash than the 7Fs themselves?

Thanks for the detailed info!

Also: The keyboard viewer flipping was just because I tried both my built-in MacBook keyboard and also a USB keyboard. I guess the viewer just changes to look like whatever keyboard you last hit a key on .

**Comment by percontation** [comment] 2016-03-17 23:23
Okay, just managed to get an (unreliable) crash via some combination of shift and mashing arrow keys. 

An Applescript or something to reproduce your crash would still be useful, if it's not too difficult... the arrow-key spamming worked for me once and hasn't yet again :|.

Hopefully these crashes are related, I'll take a look into fixing this soon.

**Comment by floam** [comment] 2016-03-17 23:28
I remember frrom last night it was a LOT harder to crash the builds I made myself in xcode. OTOH the one hosted at  http://ridiculousfish.com/hexfiend/ was very easy - I'm actually unsure if that is the debugger or some kind of instrumentation changing things or if it's just been partially worked around in git since then.

**Comment by floam** [comment] 2016-03-17 23:38
Crashes it every time for me: paste 7F7F7F or 080808 from somewhere else (for some reason cut from hexfiend and pasted back in can't cause it. Maybe encoding? HF has some richer format than bytes with  some metadata?) and paste it into the hex view on the left AFTER switching to overwrite mode.

**Comment by percontation** [comment] 2016-03-17 23:38
Ah, great. The binary at http://ridiculousfish.com/hexfiend/  looks/works/crashes for me exactly as you've been describing. Thanks for the help, I should be able to repro fine now.

**Comment by floam** [comment] 2016-03-17 23:48
(What *causes* the chunking you see above is just caused by the fact the initial key repeat delay hadn't occurred yet. I don't know if that's part of the actual crashing.

**Comment by percontation** [comment] 2016-03-18 00:09
Yeah, the selection thingy is weird. It seems to exhibit odd behavior in specific cases, such as "Opened a blank document, did the shift+up+backspace thing to generate 7Fs, and then do a shift+up to select stuff". I think this odd behavior corresponds with some unusual internal state, which was leading to the crash.

I think I just fixed that crash, so the issues remaining are:

1. Fix slightly wonky (but harmless now, hopefully) selection behavior in rare cases
2. Workaround rdar://21783531

**Comment by floam** [comment] 2016-03-18 01:43
I suppose it would be surprising if this code were not involved Shift! Arrow keys! Messing with modifiers! Anchoring!: https://github.com/ridiculousfish/HexFiend/blob/aebb7df93d99963fb9e04c7d1bbdf42176e86ed0/app/sources/DiffDocument.m#L286-L299

But I never played with diffs.

**Comment by floam** [comment] 2016-08-30 00:56
By golly I think they did it!

The bug itself with the strange behavior I haven't been able to reproduce in 10.12 for like 5 seed releases.

And the problem that was on HF's end that would have otherwise plagued users of other OS X releases you already fixed. Probably could close this up. Thanks!

**Comment by percontation** [comment] 2016-08-30 01:39
Nice! Thanks for all the help.

**Comment by floam** [comment] 2016-09-01 03:51
I was a bit premature. I'm not seeing 0x08/0x7Fs in my clipboard anymore and e.g. the single-line Find field cannot select the non-existent line above the current line, but Hex Fiend isn't actually acting much differently. I'll recompile it and see if maybe the fix only occurs after a recompile or uses the 10.12 SDK.

**Comment by kainjow** [comment] 2016-11-15 18:04
Is there still an issue here with the latest changes in master?

**Comment by kainjow** [comment] 2016-11-18 04:37
v2.4 was just released. I'll close this for now. If there are still bugs specific to this please reopen or create a new issue.

**Closed by kainjow** 2016-11-18 04:37 UTC
